version: "3.9"

services:
  python:
    container_name: python_container
    build: ./Docker/python
    command: "python -m http.server && pip install --upgrade pip $$ pip install poetry"
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/src/python/api
    working_dir: /usr/src/python/api

  db:
    container_name: mysql_container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: python_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - python-hobby-volume:/var/lib/mysql
      - ./Docker/mysql/my.conf:/etc/mysql/my.conf
volumes:
  python-hobby-volume:
